<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.5.14</version>
        <relativePath/>
    </parent>
    <groupId>pl.least-squares-algorithms</groupId>
    <artifactId>least-squares-algorithms</artifactId>
    <version>1.0.0</version>
    <name>least-squares-algorithms</name>
    <description>Least Squares Algorithms Application - API</description>
    <packaging>pom</packaging>

    <modules>
        <module>approximation-properties-service</module>
        <module>approximation-service</module>
        <module>data-series-service</module>
        <module>user-service</module>
        <module>approximation-core</module>
    </modules>

    <properties>
        <java.version>21</java.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>

        <maven-compiler-plugin.version>3.15.0</maven-compiler-plugin.version>
        <jjwt.version>0.13.0</jjwt.version>
        <jama.version>1.0.3</jama.version>
        <ejml-all.version>0.45.0</ejml-all.version>
        <lombok.version>1.18.46</lombok.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>io.jsonwebtoken</groupId>
                <artifactId>jjwt-api</artifactId>
                <version>${jjwt.version}</version>
            </dependency>
            <dependency>
                <groupId>gov.nist.math</groupId>
                <artifactId>jama</artifactId>
                <version>${jama.version}</version>
            </dependency>
            <dependency>
                <groupId>org.ejml</groupId>
                <artifactId>ejml-all</artifactId>
                <version>${ejml-all.version}</version>
            </dependency>
            <dependency>
                <groupId>org.projectlombok</groupId>
                <artifactId>lombok</artifactId>
                <version>${lombok.version}</version>
                <scope>provided</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>${lombok.version}</version>
        </dependency>
    </dependencies>
</project>
