logging.level.root=INFO

#Base url
server.servlet.context-path=/api

## Data source
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/LSAA?requireSSL=false&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=aaa
spring.datasource.password=aaa123.AAA
logging.level.org.hibernate.SQL=INFO
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

## WEB
management.endpoints.web.cors.allowed-origins=http://localhost:4200

## JWT
app.jwtSecret=jwtApproximationSecretKey
app.jwtExpiration=86400

## Liquibase
spring.liquibase.change-log=classpath:/db/changelog/dbchangelog.xml

##App
number.threads=4
